#!/bin/bash
# shutdownmailer
# This script runs in the background and catches an RPi shutdown, then runs a script to send an email before leaving.
# Copyright 2015-2021 matt.breit@gmail.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Program to send alerts to user via email.

# log stdout and stderr to syslog
exec 1> >(logger -s -t $(basename $0)) 2>&1

function shutdown_alert {
	echo "Shutdown Signal Received! Sending alert mail!"
	sudo /usr/local/bin/rpi_unattended/systemmailer.sh shutdown
	sleep 5
	exit $1
}

trap shutdown_alert SIGHUP SIGINT SIGTERM

while true
do
	sleep 10s
done
